version: "3"
services:
  admin-server:
    container_name: admin-server
    image: texmexryan/admin-server
    ports:
      - 9000:9000
    
  discovery-server:
    container_name: discovery-server
    image: texmexryan/discovery-server
    ports:
      - 8761:8761
     depends on:
      - admin-server 
   
  pokemon-service:
    container_name: pokemon-service
    image: texmexryan/pokemon-service
    ports:
      - 8081:8080
      depends on:
      - discovery-server
  trainer-service:
    container_name: trainer-service
    image: texmexryan/trainer-service
    ports:
      - 8091:8080
    depends on:
      - pokemon-service  


