version: '3'
services:
  admin-server:
    container-name: admin-server
    image: texmexryan/admin-server
    ports:
      - 9000:9000
      discovery-server:
        container-name: discovery-server
        image: texmexryan/discovery-server
        ports:
          - 8761:8761

